content:
  - name: posts
    label: Posts
    path: src/content/blog
    type: collection
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: body
        label: Body
        type: rich-text